"""Attack chain validation.

These expectations were written down BEFORE the engine was run, which is what
separates validation from a regression fixture. Fixtures elsewhere are
generated by running the engine so they cannot drift from it; here the point is
the opposite - the expected verdict must be independent of the engine, or the
test proves only that the engine agrees with itself.

Each negative fixture is its positive with that chain's own break_chain fix
applied and nothing else changed. So a passing negative is evidence for the
claim we make to an evaluator: applying the single recommended control removes
the path.
"""

import pathlib

import pytest

from engine.audit import run_audit

SAMPLES = pathlib.Path(__file__).resolve().parents[1] / "samples"

# fixture stem -> (chain_id or None, contributing findings in `requires` order)
EXPECTED = {
    "chain_mgmt_takeover_pos": (
        "CHAIN-NET-MGMT-TAKEOVER",
        ["CIS-NET-004", "CIS-NET-001", "CIS-NET-006", "CIS-NET-011"],
    ),
    "chain_mgmt_takeover_neg": (None, []),
    "chain_snmp_control_pos": (
        "CHAIN-NET-SNMP-CONTROL",
        ["CIS-NET-008", "CIS-NET-009", "CIS-NET-011"],
    ),
    "chain_snmp_control_neg": (None, []),
    "chain_cred_exposure_pos": (
        "CHAIN-NET-CRED-EXPOSURE",
        ["CIS-NET-005", "CIS-NET-006", "CIS-NET-007", "CIS-NET-003"],
    ),
    "chain_cred_exposure_neg": (None, []),
}


def _audit(stem):
    path = SAMPLES / f"{stem}.cfg"
    assert path.exists(), f"missing fixture: {path}"
    return run_audit(path.read_text(encoding="utf-8"), "cisco_ios")


@pytest.mark.parametrize("stem", sorted(EXPECTED))
def test_chain_verdict(stem):
    chain_id, contributing = EXPECTED[stem]
    paths = _audit(stem)["attack_paths"]

    if chain_id is None:
        assert paths == [], (
            f"{stem} applies the break_chain fix and must fire nothing, "
            f"got {[p['chain_id'] for p in paths]}"
        )
        return

    # Exactly one chain: a fixture that fires two is not isolating anything.
    assert [p["chain_id"] for p in paths] == [chain_id]
    assert paths[0]["contributing_findings"] == contributing


@pytest.mark.parametrize(
    "pos,neg",
    [
        ("chain_mgmt_takeover_pos", "chain_mgmt_takeover_neg"),
        ("chain_snmp_control_pos", "chain_snmp_control_neg"),
        ("chain_cred_exposure_pos", "chain_cred_exposure_neg"),
    ],
)
def test_negative_differs_only_by_the_break_chain_fix(pos, neg):
    """The fix named in break_chain is the one that stops firing.

    Guards against a negative fixture that silences the chain by accident -
    by dropping some other link - which would make the pair prove nothing.
    """
    fired = _audit(pos)["attack_paths"][0]
    fix_rule = fired["break_chain"]["fix_rule"]

    assert fix_rule in fired["contributing_findings"]

    neg_ids = {f["rule_id"] for f in _audit(neg)["findings"]}
    assert fix_rule not in neg_ids, (
        f"{neg} should satisfy {fix_rule}, but it still fires"
    )

    # Every other link is untouched, so the only difference is the fix.
    others = [r for r in fired["contributing_findings"] if r != fix_rule]
    still_firing = [r for r in others if r in neg_ids]
    assert still_firing == others, (
        f"{neg} changed more than the break_chain fix; "
        f"expected {others} to still fire, got {still_firing}"
    )
