set version 21.4R3-S4.9
set system host-name EDGE-SRX-01
set system root-authentication encrypted-password "$6$abcdef"
set system login user admin class super-user authentication plain-text-password
set system login user netops class super-user authentication plain-text-password
set system services telnet
set system services ssh
set system services web-management http interface ge-0/0/0.0
set system syslog file messages any notice
set snmp community public authorization read-only
set snmp community private authorization read-write
set snmp location DC1-Mumbai
set system ntp server 10.10.0.250
set protocols lldp interface all
set interfaces ge-0/0/0 unit 0 family inet address 203.0.113.10/29
set security zones security-zone untrust interfaces ge-0/0/0.0
set routing-options static route 0.0.0.0/0 next-hop 203.0.113.9